### PR TITLE
add `untranslated_pages_behavior` config option

### PR DESCRIPTION
**Pull request by benface**
This option is useful when you have some pages that should only be available in one or a few languages but not all. Right now, you can do that in Grav by creating the page in the languages you don't want to translate and setting `published` to `false`, but the langswitcher will still try to go to those pages, resulting in a 404. This option makes it so that when the user switches to another language and the current page doesn't exist in that language, or it exists but it's not published, it goes to the home route instead.

### CODE REVIEW

**Comment by benface** [comment]
@flaviocopes Thoughts? :)

**Comment by flaviocopes** [comment]
Two thoughts:

- by default, the original behavior should be applied to avoid changing how existing sites work when they update
- maybe add another option to actually hide the language link, if it's not translated?

**Review by flaviocopes — CHANGES_REQUESTED** [review]
the original behavior should be applied to avoid changing how existing sites work when they update

**Comment by benface** [comment]
@flaviocopes Done! Both of your suggestions.

**Comment by benface** [comment]
@flaviocopes Bump :)

**Comment by flaviocopes** [comment]
Tested and works like described, thanks!

**Comment by benface** [comment]
Thank you! :)

**Pull request merged**
